// Police / Law Enforcement Radio Codes
// Source: https://www.zipscanners.com/blogs/learn/police-codes
// Note: meanings vary by agency. This is the APCO / common-set reference list.

const DATA = {
  "starter": {
    label: "Starter (Top 15)",
    description: "The 15 most-used codes you'll hear on real scanner traffic. Start here.",
    highlight: true,
    excludeFromAll: true,
    cards: [
      { code: "10-4",  meaning: "Acknowledgment (OK)",       notes: "Most famous code in radio history." },
      { code: "10-7",  meaning: "Out of service",            notes: "Off duty / fueling / unavailable." },
      { code: "10-8",  meaning: "In service",                notes: "Available for calls." },
      { code: "10-9",  meaning: "Repeat",                    notes: "\"Say again.\"" },
      { code: "10-20", meaning: "Location",                  notes: "\"What's your 20?\"" },
      { code: "10-22", meaning: "Disregard",                 notes: "Cancel the assignment." },
      { code: "10-23", meaning: "Arrived at scene",          notes: "On location." },
      { code: "10-31", meaning: "Crime in progress",         notes: "Active incident." },
      { code: "10-32", meaning: "Man with gun",              notes: "Armed subject — high priority." },
      { code: "10-33", meaning: "Emergency — stand by",      notes: "Clear the radio for priority traffic." },
      { code: "10-50", meaning: "Accident (F/PI/PD)",        notes: "Fatal / Injury / Property Damage." },
      { code: "10-76", meaning: "En-route",                  notes: "On the way." },
      { code: "10-77", meaning: "ETA",                       notes: "Estimated time of arrival." },
      { code: "10-78", meaning: "Need assistance",           notes: "Officer needs help." },
      { code: "10-99", meaning: "Wanted / stolen indicated", notes: "Warrant / stolen hit confirmation." }
    ]
  },

  "10-codes": {
    label: "10-Codes",
    description: "APCO-published radio brevity codes (1940). Still dominate patrol channels.",
    cards: [
      { code: "10-0",  meaning: "Caution",                       notes: "Use with discretion" },
      { code: "10-1",  meaning: "Unable to copy",                notes: "Signal weak" },
      { code: "10-2",  meaning: "Signal good",                   notes: "" },
      { code: "10-3",  meaning: "Stop transmitting",             notes: "Cease radio traffic" },
      { code: "10-4",  meaning: "Acknowledgment (OK)",           notes: "Most famous" },
      { code: "10-5",  meaning: "Relay",                         notes: "Transmit to another unit" },
      { code: "10-6",  meaning: "Busy",                          notes: "Stand by" },
      { code: "10-7",  meaning: "Out of service",                notes: "Off duty / fuel" },
      { code: "10-8",  meaning: "In service",                    notes: "Available" },
      { code: "10-9",  meaning: "Repeat",                        notes: "Say again" },
      { code: "10-10", meaning: "Fight in progress",             notes: "High priority" },
      { code: "10-11", meaning: "Dog case",                      notes: "Animal control" },
      { code: "10-12", meaning: "Stand by / Visitors present",   notes: "Sensitive info" },
      { code: "10-13", meaning: "Weather conditions",            notes: "Road report" },
      { code: "10-14", meaning: "Escort / Convoy",               notes: "" },
      { code: "10-15", meaning: "Prisoner in custody",           notes: "" },
      { code: "10-16", meaning: "Pick up prisoner",              notes: "Transport request" },
      { code: "10-17", meaning: "Pick up papers",                notes: "Documents" },
      { code: "10-18", meaning: "Urgent",                        notes: "Complete quickly" },
      { code: "10-19", meaning: "Return to station",             notes: "HQ" },
      { code: "10-20", meaning: "Location",                      notes: "\"What's your 20?\"" },
      { code: "10-21", meaning: "Call by telephone",             notes: "Phone contact" },
      { code: "10-22", meaning: "Disregard",                     notes: "Cancel assignment" },
      { code: "10-23", meaning: "Arrived at scene",              notes: "On location" },
      { code: "10-24", meaning: "Assignment completed",          notes: "" },
      { code: "10-25", meaning: "Report in person",              notes: "Meet at HQ or scene" },
      { code: "10-26", meaning: "Detaining subject",             notes: "Subject held" },
      { code: "10-27", meaning: "Driver-license info",           notes: "Request check" },
      { code: "10-28", meaning: "Vehicle registration",          notes: "Plate lookup" },
      { code: "10-29", meaning: "Check for wanted",              notes: "Warrants / stolen" },
      { code: "10-30", meaning: "Illegal use of radio",          notes: "Unnecessary traffic" },
      { code: "10-31", meaning: "Crime in progress",             notes: "" },
      { code: "10-32", meaning: "Man with gun",                  notes: "Armed subject" },
      { code: "10-33", meaning: "Emergency — stand by",          notes: "Radio priority" },
      { code: "10-34", meaning: "Riot",                          notes: "Civil disturbance" },
      { code: "10-35", meaning: "Major crime alert",             notes: "" },
      { code: "10-36", meaning: "Correct time",                  notes: "Request / provide" },
      { code: "10-37", meaning: "Suspicious vehicle",            notes: "Or subject" },
      { code: "10-38", meaning: "Stopping suspicious vehicle",   notes: "Code 5 stop" },
      { code: "10-39", meaning: "Urgent — lights & siren",       notes: "Code 3" },
      { code: "10-40", meaning: "Silent run — no lights",        notes: "Code 2" },
      { code: "10-41", meaning: "Begin shift",                   notes: "" },
      { code: "10-42", meaning: "End shift",                     notes: "" },
      { code: "10-43", meaning: "Information",                   notes: "Message" },
      { code: "10-44", meaning: "Permission to leave",           notes: "Break / coffee" },
      { code: "10-45", meaning: "Animal carcass",                notes: "Road hazard" },
      { code: "10-46", meaning: "Assist motorist",               notes: "Disabled vehicle" },
      { code: "10-47", meaning: "Emergency road repairs",        notes: "" },
      { code: "10-48", meaning: "Traffic standard repair",       notes: "" },
      { code: "10-49", meaning: "Traffic light out",             notes: "" },
      { code: "10-50", meaning: "Accident (F/PI/PD)",            notes: "Fatal / Injury / Damage" },
      { code: "10-51", meaning: "Wrecker needed",                notes: "Tow truck" },
      { code: "10-52", meaning: "Ambulance needed",              notes: "" },
      { code: "10-53", meaning: "Road blocked",                  notes: "" },
      { code: "10-54", meaning: "Livestock on highway",          notes: "" },
      { code: "10-55", meaning: "Drunk driver",                  notes: "DUI suspect" },
      { code: "10-56", meaning: "Intoxicated pedestrian",        notes: "" },
      { code: "10-57", meaning: "Hit & run",                     notes: "" },
      { code: "10-58", meaning: "Direct traffic",                notes: "" },
      { code: "10-59", meaning: "Convoy / escort",               notes: "" },
      { code: "10-60", meaning: "Squad in vicinity",             notes: "" },
      { code: "10-61", meaning: "Personnel in area",             notes: "" },
      { code: "10-62", meaning: "Reply to message",              notes: "" },
      { code: "10-63", meaning: "Prepare to copy",               notes: "" },
      { code: "10-64", meaning: "Message for local delivery",    notes: "" },
      { code: "10-65", meaning: "Net message assignment",        notes: "" },
      { code: "10-66", meaning: "Missing person",                notes: "" },
      { code: "10-67", meaning: "Clear to read net message",     notes: "" },
      { code: "10-68", meaning: "Dispatch information",          notes: "" },
      { code: "10-69", meaning: "Message received",              notes: "" },
      { code: "10-70", meaning: "Fire alarm",                    notes: "" },
      { code: "10-71", meaning: "Advise nature of fire",         notes: "" },
      { code: "10-72", meaning: "Report progress of fire",       notes: "" },
      { code: "10-73", meaning: "Smoke report",                  notes: "" },
      { code: "10-74", meaning: "Negative",                      notes: "No" },
      { code: "10-75", meaning: "In contact with",               notes: "Subject / unit" },
      { code: "10-76", meaning: "En-route",                      notes: "" },
      { code: "10-77", meaning: "ETA",                           notes: "Estimated arrival" },
      { code: "10-78", meaning: "Need assistance",               notes: "Officer needs help" },
      { code: "10-79", meaning: "Notify coroner",                notes: "" },
      { code: "10-80", meaning: "Chase in progress",             notes: "Pursuit" },
      { code: "10-81", meaning: "Breathalyser report",           notes: "Intox test" },
      { code: "10-82", meaning: "Reserve lodging",               notes: "" },
      { code: "10-83", meaning: "School crossing duty",          notes: "" },
      { code: "10-84", meaning: "If meeting ___, advise ETA",    notes: "" },
      { code: "10-85", meaning: "Delayed due to ____",           notes: "" },
      { code: "10-86", meaning: "Officer on duty",               notes: "" },
      { code: "10-87", meaning: "Pickup/distribute checks",      notes: "" },
      { code: "10-88", meaning: "Advise phone number",           notes: "" },
      { code: "10-89", meaning: "Bomb threat",                   notes: "" },
      { code: "10-90", meaning: "Bank alarm",                    notes: "" },
      { code: "10-91", meaning: "Prowler",                       notes: "" },
      { code: "10-92", meaning: "Improperly parked vehicle",     notes: "" },
      { code: "10-93", meaning: "Blockade",                      notes: "Road closed" },
      { code: "10-94", meaning: "Drag racing",                   notes: "" },
      { code: "10-95", meaning: "Prisoner in custody",           notes: "" },
      { code: "10-96", meaning: "Mental subject",                notes: "" },
      { code: "10-97", meaning: "Check (test) signal",           notes: "Radio check" },
      { code: "10-98", meaning: "Assignment finished",           notes: "Available" },
      { code: "10-99", meaning: "Wanted / stolen indicated",     notes: "Hit confirmation" }
    ]
  },

  "11-codes": {
    label: "11-Codes",
    description: "Traffic-focused codes used primarily by Western U.S. agencies.",
    cards: [
      { code: "11-10", meaning: "Take report",                 notes: "" },
      { code: "11-12", meaning: "Dead animal",                 notes: "" },
      { code: "11-24", meaning: "Abandoned vehicle",           notes: "" },
      { code: "11-25", meaning: "Traffic hazard",              notes: "" },
      { code: "11-26", meaning: "Disabled vehicle",            notes: "" },
      { code: "11-27", meaning: "DL check – wants/warrants",   notes: "" },
      { code: "11-28", meaning: "Vehicle registration check",  notes: "" },
      { code: "11-40", meaning: "Advise if ambulance needed",  notes: "" },
      { code: "11-41", meaning: "Ambulance needed",            notes: "" },
      { code: "11-44", meaning: "Fatality (coroner)",          notes: "" },
      { code: "11-48", meaning: "Furnish transportation",      notes: "" },
      { code: "11-51", meaning: "Escort",                      notes: "" },
      { code: "11-52", meaning: "Funeral detail",              notes: "" },
      { code: "11-54", meaning: "Suspicious vehicle",          notes: "" },
      { code: "11-55", meaning: "Officer being followed",      notes: "" },
      { code: "11-56", meaning: "Citizen being followed",      notes: "" },
      { code: "11-79", meaning: "TC – ambulance en-route",     notes: "Traffic collision" },
      { code: "11-80", meaning: "TC – major injury",           notes: "Traffic collision" },
      { code: "11-81", meaning: "TC – minor injury",           notes: "Traffic collision" },
      { code: "11-82", meaning: "TC – property damage",        notes: "Traffic collision" },
      { code: "11-83", meaning: "TC – unknown injuries",       notes: "Traffic collision" },
      { code: "11-84", meaning: "Direct traffic",              notes: "" },
      { code: "11-85", meaning: "Tow truck needed",            notes: "" },
      { code: "11-86", meaning: "Special detail",              notes: "" },
      { code: "11-87", meaning: "Assist fire department",      notes: "" },
      { code: "11-98", meaning: "Meet at location",            notes: "" },
      { code: "11-99", meaning: "Officer needs help (urgent)", notes: "Critical" }
    ]
  },

  "signals": {
    label: "Signal Codes",
    description: "Regional signal calls used instead of 10-codes for brevity.",
    cards: [
      { code: "Signal 1",   meaning: "Drunk driver",              notes: "" },
      { code: "Signal 2",   meaning: "Intoxicated person",        notes: "" },
      { code: "Signal 3",   meaning: "Hit & run",                 notes: "" },
      { code: "Signal 4",   meaning: "Accident",                  notes: "" },
      { code: "Signal 5",   meaning: "Murder",                    notes: "" },
      { code: "Signal 6",   meaning: "Escaped prisoner",          notes: "" },
      { code: "Signal 7",   meaning: "Dead body",                 notes: "" },
      { code: "Signal 8",   meaning: "Missing person",            notes: "" },
      { code: "Signal 9",   meaning: "Stolen vehicle",            notes: "" },
      { code: "Signal 10",  meaning: "Stolen items",              notes: "" },
      { code: "Signal 11",  meaning: "Hit & run – injury",        notes: "" },
      { code: "Signal 12",  meaning: "Reckless driving",          notes: "" },
      { code: "Signal 13",  meaning: "Suspicious person",         notes: "" },
      { code: "Signal 14",  meaning: "Information",               notes: "" },
      { code: "Signal 15",  meaning: "Special detail",            notes: "" },
      { code: "Signal 16",  meaning: "Domestic disturbance",      notes: "" },
      { code: "Signal 17",  meaning: "Complaint",                 notes: "" },
      { code: "Signal 18",  meaning: "Felony in progress",        notes: "" },
      { code: "Signal 19",  meaning: "Misdemeanor",               notes: "" },
      { code: "Signal 20",  meaning: "Mental subject",            notes: "" },
      { code: "Signal 21",  meaning: "Burglary in progress",      notes: "" },
      { code: "Signal 22",  meaning: "Disturbance",               notes: "" },
      { code: "Signal 23",  meaning: "Hold-up",                   notes: "" },
      { code: "Signal 24",  meaning: "Prowler",                   notes: "" },
      { code: "Signal 25",  meaning: "Fire",                      notes: "" },
      { code: "Signal 26",  meaning: "Detain subject",            notes: "" },
      { code: "Signal 27",  meaning: "License check",             notes: "" },
      { code: "Signal 28",  meaning: "Registration check",        notes: "" },
      { code: "Signal 29",  meaning: "Reckless driver",           notes: "" },
      { code: "Signal 30",  meaning: "Bomb threat",               notes: "" },
      { code: "Signal 31",  meaning: "Crime in progress",         notes: "" },
      { code: "Signal 32",  meaning: "Gun involved",              notes: "" },
      { code: "Signal 33",  meaning: "Emergency — radio silence", notes: "" },
      { code: "Signal 34",  meaning: "Assault",                   notes: "" },
      { code: "Signal 35",  meaning: "Rape",                      notes: "" },
      { code: "Signal 36",  meaning: "Shooting",                  notes: "" },
      { code: "Signal 37",  meaning: "Stabbing",                  notes: "" },
      { code: "Signal 38",  meaning: "Officer in danger",         notes: "" },
      { code: "Signal 39",  meaning: "Road block",                notes: "" },
      { code: "Signal 40",  meaning: "Fight",                     notes: "" },
      { code: "Signal 50",  meaning: "Dispatch duty",             notes: "" },
      { code: "Signal 60",  meaning: "Open door / window",        notes: "" },
      { code: "Signal 70",  meaning: "Improper parking",          notes: "" },
      { code: "Signal 80",  meaning: "Explosion",                 notes: "" },
      { code: "Signal 90",  meaning: "Hostage situation",         notes: "" },
      { code: "Signal 100", meaning: "Resume normal traffic",     notes: "" }
    ]
  },

  "phonetic": {
    label: "Phonetic Alphabet",
    description: "NATO phonetic alphabet for clear spelling over radio.",
    cards: [
      { code: "A", meaning: "Alpha",    notes: "" },
      { code: "B", meaning: "Bravo",    notes: "" },
      { code: "C", meaning: "Charlie",  notes: "" },
      { code: "D", meaning: "Delta",    notes: "" },
      { code: "E", meaning: "Echo",     notes: "" },
      { code: "F", meaning: "Foxtrot",  notes: "" },
      { code: "G", meaning: "Golf",     notes: "" },
      { code: "H", meaning: "Hotel",    notes: "" },
      { code: "I", meaning: "India",    notes: "" },
      { code: "J", meaning: "Juliett",  notes: "" },
      { code: "K", meaning: "Kilo",     notes: "" },
      { code: "L", meaning: "Lima",     notes: "" },
      { code: "M", meaning: "Mike",     notes: "" },
      { code: "N", meaning: "November", notes: "" },
      { code: "O", meaning: "Oscar",    notes: "" },
      { code: "P", meaning: "Papa",     notes: "" },
      { code: "Q", meaning: "Quebec",   notes: "" },
      { code: "R", meaning: "Romeo",    notes: "" },
      { code: "S", meaning: "Sierra",   notes: "" },
      { code: "T", meaning: "Tango",    notes: "" },
      { code: "U", meaning: "Uniform",  notes: "" },
      { code: "V", meaning: "Victor",   notes: "" },
      { code: "W", meaning: "Whiskey",  notes: "" },
      { code: "X", meaning: "X-ray",    notes: "" },
      { code: "Y", meaning: "Yankee",   notes: "" },
      { code: "Z", meaning: "Zulu",     notes: "" }
    ]
  }
};
